ditrit/leto-modelizer

- changelog.md
- cypress/e2e/homepage.feature
- cypress/support/step_definitions/context.js
- cypress/support/step_definitions/event.js
- cypress/support/step_definitions/html.js
- cypress/support/step_definitions/localstorage.js
- src/components/card/ProjectCard.vue
- src/components/grid/ProjectGrid.vue
- src/composables/Project.js
- src/i18n/en-US/index.js
- src/pages/HomePage.vue
- tests/unit/components/card/ProjectCard.spec.js
- tests/unit/composables/Project.spec.js
closes #4 
<details>
<summary>Screenshot</summary>
</details>
> Add project list and save projects locally

- __mocks__/monaco-editor.js
- changelog.md
- cypress/e2e/modelizerpage.feature
- cypress/e2e/roundtrip.feature
- package-lock.json
- package.json
- quasar.config.js
- src/components/ModelizerNavigationBar.vue
- src/components/ModelizerTextView.vue
- src/components/editor/MonacoEditor.vue
- src/pages/ModelizerPage.vue
- tests/unit/components/ModelizerTextView.spec.js
- tests/unit/components/editor/MonacoEditor.spec.js
- tests/unit/pages/ModelizerPage.spec.js
> Feature: add monaco text editor

- changelog.md
- cypress/e2e/git/branch_menu.feature
- src/components/card/GitBranchCard.vue
- src/components/menu/GitBranchActionMenu.vue
- src/components/menu/GitBranchItemMenu.vue
- src/components/menu/GitBranchMenu.vue
- src/composables/Project.js
- src/composables/events/GitEvent.js
- src/i18n/en-US/index.js
- tests/unit/components/card/GitBranchCard.spec.js
- tests/unit/components/menu/GitBranchActionMenu.spec.js
- tests/unit/components/menu/GitBranchMenu.spec.js
- tests/unit/composables/Project.spec.js
- tests/unit/composables/events/GitEvent.spec.js
Add checkout action on branch menu.
> Feature: checkout branch

- changelog.md
- cypress/e2e/file/file_explorer.feature
- src/components/ModelizerTextView.vue
- src/composables/FileExplorer.js
- src/composables/Project.js
- tests/unit/components/ModelizerTextView.spec.js
- tests/unit/composables/FileExplorer.spec.js
- tests/unit/composables/Project.spec.js
Add root folder in file explorer with the project name as label.
If project is based upon a remote repository, the label is the remote repository name. Otherwise, the label is the local project name.
> Feature/ add root project folder

- changelog.md
- cypress/e2e/git/branch_menu_update.feature
- src/components/dialog/GitUpdateDialog.vue
- src/components/form/GitUpdateForm.vue
- src/components/menu/GitBranchActionMenu.vue
- src/components/menu/GitBranchItemMenu.vue
- src/components/menu/GitBranchMenu.vue
- src/composables/Project.js
- src/css/app.scss
- src/i18n/en-US/index.js
- src/pages/ModelizerPage.vue
- tests/unit/components/dialog/GitUpdateDialog.spec.js
- tests/unit/components/form/GitUpdateForm.spec.js
- tests/unit/components/menu/GitBranchActionMenu.spec.js
- tests/unit/composables/Project.spec.js
> Feature: pull action

- src/composables/Project.js
- tests/unit/composables/Project.spec.js
Replace git function by fs function in Project composable to get the local result instead of the remote result.
> Replace git functions by fs ones in Project composable

- changelog.md
- src/components/ModelizerModelView.vue
- src/components/ModelizerNavigationBar.vue
- src/components/ModelizerTextView.vue
- src/components/editor/MonacoEditor.vue
- src/components/form/CreateFileForm.vue
- src/composables/Project.js
- src/composables/events/PluginEvent.js
- src/pages/ModelizerPage.vue
- tests/unit/components/ModelizerModelView.spec.js
- tests/unit/components/ModelizerNavigationBar.spec.js
- tests/unit/components/ModelizerTextView.spec.js
- tests/unit/components/editor/MonacoEditor.spec.js
- tests/unit/composables/events/PluginEvent.spec.js
Parse and render, Model to Text and reverse.
> Parse and render, Model to Text and reverse.

- src/components/inputs/BooleanInput.vue
- src/components/inputs/InputWrapper.vue
- src/components/inputs/NumberInput.vue
- src/components/inputs/StringInput.vue
> Update emit declaration in inputs

- changelog.md
- src/components/FileExplorer.vue
- src/components/ModelizerTextView.vue
- src/composables/FileExplorer.js
- src/composables/PluginManager.js
- src/composables/events/FileEvent.js
- src/i18n/en-US/index.js
- tests/unit/components/FileExplorer.spec.js
- tests/unit/components/ModelizerTextView.spec.js
- tests/unit/composables/FileExplorer.spec.js
- tests/unit/composables/PluginManager.spec.js
- Add checkbox to trigger filter
- Add filter to show parsable files and folder in tree
- Update FileExplorer.js composable
> Feature : add filter to show parsable files and folder in tree

- src/components/ModelizerModelsView.vue
- src/components/card/ModelCard.vue
- src/i18n/en-US/index.js
- tests/unit/components/card/ModelCard.spec.js
Update style of :
- ModelsView
- ModelCard
> Update models page style

- changelog.md
- package-lock.json
- package.json
- quasar.config.js
- src/boot/v-viewer.js
- src/components/dialog/ImportModelTemplateDialog.vue
- src/components/dialog/NewProjectTemplateDialog.vue
- src/composables/TemplateManager.js
- tests/unit/components/dialog/ImportModelTemplateDialog.spec.js
- tests/unit/components/dialog/NewProjectTemplateDialog.spec.js
- tests/unit/composables/TemplateManager.spec.js
- Add carousel to display each schema in `NewProjectTemplateDialog`
- Display model schema in `ImportModelTemplateDialog`
- Handle zoom on click on each schema with `v-viewer` library
> Feature : Display template schema in related dialog

- changelog.md
- cypress.config.js
- cypress/e2e/ModelizerPage/ModelView/plugin/display.component.feature
- cypress/support/commands.js
- cypress/support/e2e.js
- cypress/support/step_definitions/event.js
- package-lock.json
- package.json
- src/components/ModelizerModelView.vue
- src/components/card/ComponentDefinitionCard.vue
- src/components/drawer/ComponentDropOverlay.vue
- src/i18n/en-US/index.js
- tests/unit/components/ModelizerModelView.spec.js
- tests/unit/components/card/ComponentDefinitionCard.spec.js
> Feature: component creation on drop

- changelog.md
- src/components/drawer/ComponentDetailPanel.vue
- src/i18n/en-US/index.js
- tests/unit/components/drawer/ComponentDetailPanel.spec.js
- Add checkbox to allow saving attribute field(s) in error
- Add function to handle form validation
> Feature : Force save attributes

- src/components/form/CreateModelForm.vue
- tests/unit/components/form/CreateModelForm.spec.js
Display plugin name by default inside select in CreateModelForm
> Feature : Select plugin by default

- src/components/drawer/ComponentDetailPanel.vue
- src/components/panel/AttributeSection.vue
- tests/unit/components/panel/AttributeSection.spec.js
- Fix filter in getSubAttributes function
- Fix onError event when is undefined
> Bugfix : Filter in getSubAttribute and onError functions

- changelog.md
- src/composables/PluginManager.js
- tests/unit/composables/PluginManager.spec.js
> Bugfix: delete file

- changelog.md
- quasar.config.js
- src/assets/about.json
- src/i18n/en-US/index.js
- src/layouts/MainLayout.vue
- src/pages/AboutPage.vue
- src/router/routes.js
- tests/unit/layouts/MainLayout.spec.js
> Feature : About page

- cypress/e2e/HomePage/create.project.feature
- cypress/e2e/HomePage/delete.project.feature
- cypress/e2e/HomePage/import.project.feature
- cypress/e2e/HomePage/open.project.feature
- cypress/e2e/HomePage/rename.project.feature
- cypress/e2e/RoundTrips/create.project.files.feature
- cypress/e2e/RoundTrips/create.project.template.files.feature
- cypress/e2e/RoundTrips/delete.project.feature
- cypress/e2e/RoundTrips/import.project.files.feature
- cypress/e2e/RoundTrips/import.project.template.files.feature
- cypress/e2e/RoundTrips/rename.project.feature
- cypress/resources/infra1/main.tf
- cypress/resources/infra1/provider.tf
- cypress/resources/infra2/main.tf
- cypress/resources/project-test/README.md
- cypress/resources/project-test/app.tf
- src/components/grid/ProjectGrid.vue
- Add e2e tests for creation, rename, import and delete project in home page
> Improvement: e2e for home page

- README.md
- changelog.md
- src/components/inputs/ObjectInput.vue
- tests/unit/components/inputs/ObjectInput.spec.js
> Bugfix: nested object definition

- changelog.md
- src/assets/editor/languages.js
- src/components/editor/MonacoEditor.vue
- tests/manual/SyntaxColor.md
- tests/unit/components/editor/MonacoEditor.spec.js
Integration syntax configuration from plugin
> Feature: Syntax color

- changelog.md
- src/components/ModelizerTextView.vue
- src/components/drawer/ComponentDefinitionsDrawer.vue
- src/i18n/en-US/index.js
> Feature: reorganize naviguation bar

- changelog.md
- src/components/DefaultNavigationBar.vue
- src/layouts/MainLayout.vue
- src/pages/HomePage.vue
- tests/unit/layouts/MainLayout.spec.js
> Improvement: homepage header

- changelog.md
- src/components/card/PluginsCard.vue
- src/components/dialog/CreateProjectTemplateDialog.vue
- src/components/form/CreateProjectTemplateForm.vue
- src/composables/TemplateManager.js
- src/i18n/en-US/index.js
- tests/unit/composables/TemplateManager.spec.js
> Feature: redesign create project form

- changelog.md
- package-lock.json
- package.json
- src/components/card/ProjectCard.vue
- src/components/grid/ProjectGrid.vue
- src/composables/Project.js
- src/i18n/en-US/index.js
- src/pages/HomePage.vue
> Feature: redesign project grid

- changelog.md
- cypress/e2e/HomePage/create.project.feature
- cypress/e2e/HomePage/delete.project.feature
- cypress/e2e/HomePage/import.project.feature
- cypress/e2e/HomePage/open.project.feature
- cypress/e2e/HomePage/rename.project.feature
- src/components/drawer/HomeDrawer.vue
- src/components/grid/ProjectGrid.vue
- src/components/item/ShortProjectsItem.vue
- src/i18n/en-US/index.js
- tests/unit/components/item/ShortProjectsItem.spec.js
> Feature: Add project expansion item

- changelog.md
- package-lock.json
- package.json
- src/components/ModelsView.vue
- src/components/drawer/HomeDrawer.vue
- src/components/grid/ProjectGrid.vue
- src/components/grid/TemplateGrid.vue
- src/i18n/en-US/index.js
- src/pages/HomePage.vue
> Feature: Redesign template zone and grid

- changelog.md
- cypress/e2e/HomePage/filter.project.feature
- src/components/grid/ProjectGrid.vue
- src/components/menu/GitBranchMenu.vue
- src/composables/Filter.js
- src/i18n/en-US/index.js
- tests/unit/components/grid/ProjectGrid.spec.js
- tests/unit/components/inputs/ArrayInput.spec.js
- tests/unit/components/inputs/BooleanInput.spec.js
- tests/unit/components/inputs/InputWrapper.spec.js
- tests/unit/components/inputs/LinkInput.spec.js
- tests/unit/components/inputs/NumberInput.spec.js
- tests/unit/components/inputs/ReferenceInput.spec.js
- tests/unit/components/inputs/SelectInput.spec.js
- tests/unit/components/inputs/StringInput.spec.js
- tests/unit/components/menu/GitBranchMenu.spec.js
- tests/unit/composables/Filter.spec.js
> Feature: search project bar

- changelog.md
- src/components/grid/ProjectGrid.vue
- src/components/grid/TemplateGrid.vue
- src/i18n/en-US/index.js
- src/pages/HomePage.vue
- tests/unit/components/grid/TemplateGrid.spec.js
> Feature: Templates search bar

- changelog.md
- package-lock.json
- package.json
- src/components/card/TemplateCard.vue
- src/components/grid/TemplateGrid.vue
> Improvement: template card

- .github/workflows/CI.yml
- changelog.md
- cypress/e2e/RoundTrips/create.project.files.feature
- cypress/support/step_definitions/event.js
- src/components/form/CreateModelForm.vue
> Improvement: multi plugins e2e

- changelog.md
- cypress/e2e/ModelsPage/SwitchDiagramType.feature
- src/components/ModelsView.vue
- src/components/card/DiagramFilterCard.vue
- src/components/grid/DiagramGrid.vue
- tests/unit/components/ModelsView.spec.js
> Feature: switch diagram type

- changelog.md
- cypress/e2e/HomePage/FilterProject.feature
- cypress/e2e/ModelsPage/CreateTemplate.feature
- cypress/e2e/ModelsPage/FilterTemplate.feature
- package-lock.json
- package.json
- src/components/ModelsView.vue
- src/components/card/TemplateCard.vue
- src/components/drawer/CreateDiagramDrawer.vue
- src/composables/events/DrawerEvent.js
- src/i18n/en-US/index.js
- src/layouts/ProjectLayout.vue
- src/pages/ModelsPage.vue
- src/router/routes.js
- src/router/routes/ModelsRoute.js
- tests/unit/components/ModelsView.spec.js
- tests/unit/components/drawer/CreateDiagramDrawer.spec.js
- tests/unit/composables/events/DrawerEvent.spec.js
- tests/unit/layouts/ProjectLayout.spec.js
> Feature: redesign create a diagram from template

- cypress/e2e/ModelizerPage/TextView/file/SwitchModelFile.feature
- src/layouts/ModelizerTextLayout.vue
- tests/unit/layouts/ModelizerTextLayout.spec.js
Bug appear due to new diagram management. This pr should fix this bug.
Resolved #335
> Fix selection of not parsable file should not change query path

- changelog.md
- src/components/dialog/GitCommitDialog.vue
- src/components/dialog/GitStatusDialog.vue
- src/composables/Project.js
- src/models/git/FileStatus.js
- tests/unit/components/dialog/GitCommitDialog.spec.js
- tests/unit/components/dialog/GitStatusDialog.spec.js
- tests/unit/composables/Project.spec.js
- tests/unit/models/git/FileStatus.spec.js
> Bugfix: fix upload deleted file

- changelog.md
- package-lock.json
- src/components/inputs/ArrayInput.vue
- src/components/inputs/BooleanInput.vue
- src/components/inputs/InputWrapper.vue
- src/i18n/en-US/index.js
> Bugfix: validate array item

- changelog.md
- cypress.config.js
- package-lock.json
- package.json
- src/components/drawer/ComponentDetailPanel.vue
- tests/unit/components/drawer/ComponentDetailPanel.spec.js
Fix some case of https://github.com/ditrit/leto-modelizer-plugin-core/issues/188.
> Bugfix: attribute type

- .github/workflows/CI.yml
- CONTRIBUTING.md
- README.md
- changelog.md
- cypress/e2e/Bugfix/Issue377.feature
- leto-modelizer-plugin-cli.json
- package-lock.json
- package.json
- src/components/FileExplorer.vue
- src/components/table/DiagramTable.vue
- src/composables/PluginManager.js
- src/composables/Project.js
- src/layouts/ModelizerDrawLayout.vue
- src/layouts/ModelizerTextLayout.vue
- src/pages/ModelizerDrawPage.vue
- tests/unit/components/FileExplorer.spec.js
- tests/unit/layouts/ModelizerTextLayout.spec.js
> Bugfix: manage root diagram.

- src/pages/ModelizerDrawPage.vue
> Reset draw actions in initView() from ModelizerDrawPage

- changelog.md
- package-lock.json
- package.json
- src/components/FileExplorer.vue
- tests/unit/components/FileExplorer.spec.js
> Improvement : Update file explorer

- changelog.md
- src/boot/vue-simple-acl.js
- src/components/card/DiagramsCard.vue
> Feature: CF create diagram from template

- changelog.md
- src/boot/vue-simple-acl.js
- src/components/menu/DiagramTableActionMenu.vue
- src/pages/DiagramsPage.vue
> Feature: Integrate CF delete diagram

- changelog.md
- src/boot/vue-simple-acl.js
- src/components/list/LibraryList.vue
- tests/unit/components/list/LibraryList.spec.js
> Feature: cf create component

- changelog.md
- cypress/e2e/DiagramsPage/DisplayDiagrams.feature
- src/boot/vue-simple-acl.js
- src/components/grid/TemplateGrid.vue
> Feature: Integrate CF create project from template

- changelog.md
- cypress/e2e/Bugfix/Issue370.feature
- cypress/e2e/Bugfix/Issue377.feature
- cypress/e2e/Bugfix/Issue390.feature
- cypress/e2e/Bugfix/Issue392.feature
- cypress/e2e/Bugfix/Issue407.feature
- cypress/e2e/DiagramsPage/DeleteDiagrams.feature
- cypress/e2e/DiagramsPage/DisplayDiagrams.feature
- cypress/e2e/DiagramsPage/FocusMovementDiagrams.feature
- cypress/e2e/DiagramsPage/ZoomDiagrams.feature
- cypress/e2e/ModelizerPage/Common/SwitchView.feature
- cypress/e2e/ModelizerPage/DrawView/plugin/DisplayComponent.feature
- cypress/e2e/ModelizerPage/DrawView/template/DisplayComponent.feature
- cypress/e2e/ModelizerPage/SwitchView/AddComponent.feature
- cypress/e2e/ModelizerPage/SwitchView/Delete.feature
- cypress/e2e/ModelsPage/SwitchDiagramType.feature
- cypress/e2e/RoundTrips/CreateProjectFiles.feature
- cypress/e2e/RoundTrips/DeleteProject.feature
- cypress/e2e/RoundTrips/DrawEditor.feature
- cypress/e2e/RoundTrips/Git.feature
- cypress/e2e/RoundTrips/ImportProjectFiles.feature
- cypress/e2e/RoundTrips/RenameProject.feature
- cypress/e2e/RoundTrips/SimpleProject.feature
- cypress/e2e/RoundTrips/TemplateProject.feature
- cypress/e2e/RoundTrips/TextEditor.feature
- cypress/e2e/Roundtrip.feature
- package-lock.json
- package.json
- src/components/card/DiagramsCard.vue
- src/i18n/en-US/index.js
> Feature: Merge add/create diagram buttons

- .github/workflows/CI.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- changelog.md
- cypress/e2e/Bugfix/Issue377.feature
- cypress/e2e/Bugfix/Issue390.feature
- cypress/e2e/Bugfix/Issue407.feature
- cypress/e2e/DiagramsPage/DeleteDiagrams.feature
- cypress/e2e/DiagramsPage/DisplayDiagrams.feature
- cypress/e2e/DiagramsPage/FocusMovementDiagrams.feature
- cypress/e2e/ModelizerPage/SwitchView/AddComponent.feature
- cypress/e2e/ModelizerPage/SwitchView/Delete.feature
- cypress/e2e/RoundTrips/DrawEditor.feature
- cypress/e2e/RoundTrips/SimpleProject.feature
- cypress/e2e/RoundTrips/TextEditor.feature
- cypress/resources/project-test/main.tf
- leto-modelizer-plugin-cli.json
- package-lock.json
- package.json
- src/components/drawer/ComponentDetailPanel.vue
- src/components/inputs/LinkInput.vue
- src/components/inputs/ReferenceInput.vue
- tests/unit/components/drawer/ComponentDetailPanel.spec.js
- tests/unit/components/inputs/LinkInput.spec.js
- tests/unit/components/inputs/ReferenceInput.spec.js
> Feature: integrate external
